#!/usr/bin/python3
menu = ["Iced Coffee", "Blonde Roast", "Matcha Latte", "Cold Brew", "Caramel Macchiato", "Pumpkin Spice Latte",
        "Peppermint Mocha", "Iced Green Lemonade", "Mango Dragonfruit Refresher", "Iced Dirty Chai Latte"]

def view_menu():
  print("\n************")
  print("STAR-COFFEE MENU") 
  for ind, val in enumerate(menu):
    print(str(ind + 1), ":", val)
  
  
def place_order():
    order = []
    while True:
        item_number = input("\nWhat would you like to order? (1-10, done to exit): ")
        if item_number.lower() == "done":
            break
        order.append(int(item_number))
    print("\nThank you for your order! Here is your order:\n")
    for item in order:
        print(menu[item-1])

while True:
    print("\n************\n")
    print("1. View Menu")
    print("2. Order")
    print("3. View Order")
    print("4. Exit")
    print("************\n")
    option = input("Pick a menu option: ")
    if option == "1":
        view_menu()
    elif option == "2":
        place_order()
    elif option == "3":
        if len(menu) == 0:
            print("Your order is empty.")
        else:
            print("Here is your order:")
            for item in menu:
                print(item)
    elif option == "4":
        print("\nHave a nice day!")
        break
    else:
        print("Invalid option. Please choose again.")
