#!/bin/python3 ⋯
#https://replit.com/@ba00001/SEUN11FORECAST?v=1
# Complete the 'playGolf' function below.
#
# The function accepts following parameters:
# 1. STRING outlook
# 2. STRING windy
# 3. STRING humidity
#
def playGolf(outlook, windy, humidity):
# Write your code here
  if outlook == "rainy":
    if windy == "True":
      if humidity == "high":
          print("play")
else:
print("don't play")
elif outlook == "overcast":
print("play")
elif outlook == "sunny":
if humidity == "high":
print("don't play")
else:
print("play")
if __name__ == '__main__': ⋯

