#!/usr/bin/python3
#https://replit.com/@ba00001/SEUN2TU1Randompassword?v=1
#password generator

import random
import string


#First define function

def password_generator():
    random_number = ''.join(str(random.randint(0, 9)) for _ in range(4))
    random_letter = ''.join(random.choice(string.ascii_letters) for _ in range(4))
  
    return random_letter + random_number
    

#Second
print(password_generator())
