#!/usr/bin/python3
#https://replit.com/@ba00001/SEUN1TU2Madlib?v=1
adjective = input("Whats your favorite adjective? ")
noun = input("Whats your favorite noun? ")
animal = input("Whats your favorite animal? ")
sound = input("Whats your favorite sound? ")

#f-strings for string interpolation
print(f"The {adjective} {noun} jumped over the {animal} and made a {sound}")

#print("The " + adjective + " " + noun + " jumped over the " + animal + " and made a " + sound)
